In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('flipkart_helpcentre.csv')
df.head()

,Topic,Question,Answer
0,Delivery related,What should I do if my order is approved but h...,Sellers usually ship orders 1-2 business days ...
1,Delivery related,Can I take the shipment after opening and chec...,"As per company policy, a shipment can't be ope..."
2,Delivery related,How quickly can I get my order delivered?,Orders will be delivered by the date you see o...
3,Delivery related,What are the standard shipping speeds and deli...,Standard Delivery charges and shipping timelin...
4,Delivery related,When will I get my order once its status chang...,"Once an order is out for delivery, please wait..."

In [19]:
df.shape

(807, 3)

In [20]:
df.columns

Index(['Topic', 'Question', 'Answer'], dtype='object')

In [5]:
df.describe()

,Topic,Question,Answer
count,807,807,807
unique,42,795,798
top,SuperCoins,The address while ordering the Hero MotoCorp 2...,You can contact the brand authorised dealer fo...
freq,63,2,2

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 807 entries, 0 to 806
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Topic     807 non-null    object
 1   Question  807 non-null    object
 2   Answer    807 non-null    object
dtypes: object(3)
memory usage: 19.0+ KB

In [27]:
topic_counts = df.groupby("Topic", sort=False)["Question"].count().reset_index()
# Rename column
topic_counts.columns = ["Topic", "Count"]
topic_counts

                                      Topic  Count
0                          Delivery related     35
1                         Open box delivery     12
2                      Login and my account     14
3                           Refunds related     21
4                              Flipkart EMI     60
5                                   Payment     33
6                         Bajaj Finserv EMI     16
7                   EMI / Pre-approved loan     11
8                   Credit Card No Cost EMI     15
9            Flipkart Axis Bank Credit Card     19
10                 Returns & Pickup related      2
11                           Return related     21
12                           Pickup related     10
13                     Cancellation related      6
14                                  Grocery     26
15                               SuperCoins     63
16                            Flipkart Plus     17
17                                  Flights     26
18                                   Hotels     10
19                                    BLACK     14
20                               2 Wheelers     25
21                                    Ather      1
22                            Hero MotoCorp     14
23                     Old Product exchange     18
24                          Invoice related      4
25                      Selling on Flipkart      1
26                          Product Reviews      3
27            Infringement & Security Issue      2
28                     Pre Purchase Queries     32
29                                 Warranty      7
30                               Gift Cards     25
31                                   Offers     12
32  Installation and Uninstallation related     10
33                            Personal Loan     10
34                                Recharges     16
35                      2 Wheeler Insurance     22
36                             Flipkart UPI     30
37                                   DOR TV     32
38                                  Minutes     48
39                                     Fees      4
40                           superPay Later     25
41                            superPay in 3     35

In [35]:
new_df = pd.DataFrame({
    'Question': df['Question'],
    'Answer': df['Answer']
})

new_df

,Question,Answer
0,What should I do if my order is approved but h...,Sellers usually ship orders 1-2 business days ...
1,Can I take the shipment after opening and chec...,"As per company policy, a shipment can't be ope..."
2,How quickly can I get my order delivered?,Orders will be delivered by the date you see o...
3,What are the standard shipping speeds and deli...,Standard Delivery charges and shipping timelin...
4,When will I get my order once its status chang...,"Once an order is out for delivery, please wait..."
5,Why am I unable to order products like televis...,The delivery of large category products at a p...
6,Are faster delivery options like Same Day & In...,"No, however, we try our best to have your item..."
7,What should I do if I find the package open or...,You can reject the delivery at the doorstep. H...
8,Why did the delivery executive refuse to picku...,"When returning a product, it is important to s..."
9,Can my order be prioritised or delivered faster?,"Order delivery dates can't be changed, since t..."
10,The delivery of my order is delayed. What shou...,In the event that the delivery of your order i...
11,My order status is delivered but I have not go...,- See if any of your neighbours/friends/relati...
12,How do I track my order details?,You can view your order details on the 'Orders...
13,Can I collect the product from warehouse/hub?,"As a security measure, orders cannot be picked..."
14,How can I modify/add an alternate number for t...,You can modify the existing delivery contact n...
15,"How can I check which address I provided, and ...",You can check your address details on the Orde...
16,Why is my order status not updated to delivered ?,It may take up to 24 hours for the order statu...
17,Why did I receive a message about delivery fai...,This can happen due to an unexpected issue. If...
18,When will I get my order once it is Out for De...,Orders out for delivery will reach you by 11 P...
19,When will I get my order if I miss a delivery ...,"If you miss a delivery, another attempt is mad..."
20,"My order has reached the nearest delivery hub,...",The delivery partner delivering your order is ...
21,Why does the estimated delivery time vary for ...,Delivery timelines are determined by various f...
22,I have a complaint about the delivery executiv...,You can contact our Customer Support team with...
23,Why can't I track my order even though it has ...,Courier services usually take upto 24 hours to...
24,How do I contact the delivery partner?,Here are the contact details of some of the le...
25,Why was my order not delivered/delivery attemp...,"Sometimes, an order may be undelivered due to ..."
26,What do the different order statuses in 'My Or...,The different order statuses are as mentioned ...
27,Can I get my orders delivered at a specific time?,Orders for a few items from certain categories...
28,Can I club my orders from different sellers to...,"Currently, there is no option to club orders f..."
29,Will the delivery be tried again if I'm not ab...,Delivery partners make sure that the delivery ...
30,Why are faster delivery options not available ...,Faster delivery options may not be available a...
31,Why did I receive a new delivery date for my o...,A new delivery date is provided for certain or...
32,I can see that order for a new item has been p...,If your order was lost or damaged during trans...
33,How do I track my order?,"Once your order gets shipped, a tracking ID ge..."
34,Why are the Delivery Executive details invalid?,"-For Ekart orders, once the order is out for d..."
35,Is Open Box delivery available for all the pro...,"No, the Open Box Delivery option is available ..."
36,How will I get to know if the chosen item is e...,You will get to know if a product has an Open ...
37,When will I receive the OTP?,You will receive the OTP via an SMS when the p...
38,When do I need to share the OTP with the deliv...,You should share the OTP with the delivery exe...
39,Is Open Box delivery available for orders plac...,"Yes, the Open Box delivery option is not depen..."
40,What if the product turns out to be defective ...,In the unlikely event of an item being defecti...
41,What if I don’t want the open box delivery opt...,"Currently, eligible products can only be deliv..."
42,Can a friend or family member accept the packa...,"Yes, however, please ensure that they thorough..."
43,What if I realise that an accessory is missing...,"Once an Open Box delivery has been accepted, a..."
44,Why am I not getting an Open-Box delivery opti...,"Currently, the Open-Box delivery service is pr..."
45,What is Open Box delivery?,Open box delivery is a benificial program for ...
46,"What if the product is different, damaged or m...",Request you to not to accept the produt delive...
47,Can I reactivate my inactive Flipkart account?,"Yes. To reactivate your Flipkart account, simp..."
48,Do I need to verify my mobile number or email ...,As the verification step is a one time process...
49,What is an OTP or verification code?,An OTP (One Time Password) or verification cod...
50,Why do I need to verify my mobile number or em...,To make sure that your account details are alw...
51,Can I use an international number to sign up?,"Yes, you can use an international number to si..."
52,How can I use my mobile number to login on the...,"To log into the Flipkart mobile app, update yo..."
53,"I'm getting an error message that says, 'You'v...",If a wrong code is entered for verification mo...
54,Can I use a corporate email ID to sign up?,"Yes, you can use a corporate email ID. However..."
55,How can I add a new delivery address to my Fli...,"To add a new delivery address, follow these si..."
56,What should I do if I don't get the OTP or ver...,Network issues sometimes delay OTP-based SMS. ...
57,How can I change the email ID linked with my F...,"To change the email ID, log in to your Flipkar..."
58,How can I deactivate my Flipkart account?,"To deactivate your Flipkart account, follow th..."
59,What to do if I am unable to login via website?,Please check if your internet connection is st...
60,How to add GSTIN number to my Flipkart account?,You can add a GSTIN number to an order but not...
61,What are the modes of refund available after c...,The different modes of refund available are:\n...
62,Why does it take time for the refund amount to...,"Once the refund has been processed, the bank t..."
63,Will I get a complete refund if the item is ca...,"Yes, you will get a complete refund to the ext..."
64,Can I get the refund for the item to any other...,"No, the refund for an order placed using the B..."
65,Can I get the refund for the item through any ...,"No, the refund mode cannot be changed for an o..."
66,Can I get the refund for the item through any ...,"No, the refund for an order placed using the '..."
67,Where will the refunds for my order be credited?,"For payments made through cash/POS, you can ch..."
68,Why have I only received a part of the refund ...,Refunds are processed item wise and you may se...
69,When will the refund amount for my order(s) be...,The refunds for your order(s) are processed at...
70,How can I know the status of my refund?,You can visit 'My Orders' to know the status o...
71,What are the refund timelines if I cancel or r...,The refund timelines will depend on the paymen...
72,When are refunds provided for orders?,You can get a refund for an order if you cance...
73,I've still not received the refund in my bank ...,If you've received an SMS confirming the refun...
74,What should I do if refund gets failed?,"If your refund has failed, please visit the 'O..."
75,How can I identify the UPI details?,"Not to worry. If your order is prepaid, you ca..."
76,What does ARN number mean?,ARN/UTR/BRN number is the refund reference num...
77,How can I add bank account details?,"Not to worry. To add a bank account, just foll..."
78,How do I link my bank account in Flipkart?,"Not to worry. To add a bank account, you just ..."
79,How can I change/update my bank account details?,The system will show you your previously saved...
80,How do I upload a new bank statement for a res...,To upload a bank statement for a resolved quer...
81,How will I get my refund for returning an item...,"In case of cash on delivery, you will have to ..."
82,What is Flipkart EMI?,Flipkart EMI is a payment mode available on th...
83,What are the factors that affect my Cibil score?,Your Cibil score can be affected due to any of...
84,How will I know the due date of Flipkart EMI b...,You can see this information in the 'Account' ...
85,What are the benefits of Flipkart EMI?,Flipkart EMI offers the below benefits:\n\n- Q...
86,Who can use Flipkart EMI?,This EMI facility is currently available to on...
87,What is my pre-qualified loan offer on Flipkar...,Visit 'Account' > 'Flipkart EMI' > 'Loan Offer...
88,Why can't I see Flipkart EMI available for som...,Flipkart EMI is currently available for select...
89,Why do I need to complete KYC for availing Fli...,Flipkart EMI is a financial Loan-credit produc...
90,What is a minimum KYC? How is it different fro...,Aadhaar OTP-based e-KYC is considered a minimu...
91,How will I get to know when my minimum KYC is ...,Please visit the Flipkart EMI section under 'A...
92,How can I upgrade to full KYC?,"If you are a minimum KYC user, you can always ..."
93,What is the process for completing full KYC?,"To complete your full KYC, we will search your..."
94,What is the Central KYC Registry?,The Central KYC (C-KYC) Registry is an initiat...
95,What is Aadhaar Paperless Offline e-KYC?,Aadhaar Paperless Offline e-KYC is another mod...
96,Is my KYC/account information shared with part...,"KYC is conducted by our financial partner,..."
97,How can I place an order using Flipkart EMI on...,Here's how you can place an order:\n- Add item...
98,How can I place an order using Flipkart EMI on...,"Currently, Flipkart EMI is not available on pl..."
99,Do I need to make a down payment to buy an ite...,"No, you can place orders without making any do..."
100,What rate of interest will be incurred while a...,The interest rate and the actual interest amou...
101,How can I track my Flipkart EMI usage and tran...,Here's how you can track your Flipkart EMI usa...
102,Do I get an OTP while paying through Flipkart ...,"Yes, you may receive an OTP on your registered..."
103,Can I cancel/return my order after I've placed...,"Yes, you can cancel/return a product by visiti..."
104,I have received an SMS / Email notification fo...,Please cancel your order immediately by visiti...
105,How will Flipkart EMI bill be generated?,"You will get a single, unified bill that will ..."
106,How will I know that my Flipkart EMI bill has ...,You will receive Email / SMS / app notificatio...
107,What will happen to my Flipkart EMI dues once ...,Your past EMIs will continue to get added in t...
108,How do I pay Flipkart EMI bill?,You can pay your bill by clicking on the payme...
109,What payment modes are supported to pay the Fl...,We currently support bill payment for Flipkart...
110,Can I pay the bill using Cash / EMIs / credit ...,"No, we do not support payment of bills using c..."
111,Can I change the delivery time for my order?,Delivery time for an order cannot be changed a...
112,Can I pay only a part of the bill?,"Yes! August 2023 onwards, customers who are de..."
113,How much amount can I pay if I am making a par...,You can pay any amount starting from the minim...
114,Will my bureau be affected if I make partial p...,Partial payments let you gradually clear your ...
115,Can I pay for my unbilled transactions of Flip...,"Yes, you can pay for the unbilled transactions..."
116,Can I change the bill date or due date?,"No, we don't support changes to the bill date ..."
117,I missed the Email/SMS notification sent to me...,Don’t worry. In case you missed the first comm...
118,What happens if I don't pay my bill by the due...,Your Cibil score will be impacted if you do no...
119,What happens if I don't pay my bill even after...,Outstanding dues beyond the 5th of the month w...
120,What is EMI foreclosure?,Foreclosure option enables you to close the lo...
121,Can I foreclose my EMI loan?,"Yes, you can foreclose your Flipkart EMI loan ..."
122,Is there any charge for Flipkart EMI foreclosure?,A foreclosure charge of 3.39% of the unbilled ...
123,How can I foreclose my EMI loans?,You can foreclose your Flipkart EMI loans by c...
124,What happens if I cancel the order after forec...,You can reach out to the customer support of t...
125,How long will it take to Foreclose my loan?,It may take up to 15 working days to process t...
126,How is the foreclosure amount calculated?,The lender calculates foreclosure amount based...
127,How can I request my Flipkart EMI account clos...,You can do so by clicking here. To close your ...
128,My payment using the Flipkart EMI did not go t...,The amount will be automatically adjusted back...
129,I paid for my Flipkart order using Flipkart EM...,Your pre-qualified loan offer will be restored...
130,"Once a bill is generated, how can I get the re...",Once your refund has been processed successful...
131,What happens to any refund for orders placed u...,"If the bill has already been paid, any refund ..."
132,"I placed a return request, but the same was pe...",Please pay the total bill amount before the du...
133,What is a Processing Fee?,A Processing Fee is a nominal one time fee whi...
134,How is processing fee calculated for Flipkart ...,A fee of 1.25% + GST (no minimum cap) will be ...
135,Will the Processing fee be refunded if I cance...,"No, the Processing Fee will not be refunded po..."
136,Why is my Flipkart EMI account blocked?,Your Flipkart EMI account can be blocked due t...
137,Will the Flipkart EMI option reflect as a loan...,Flipkart EMI will reflect in your credit histo...
138,What is the cooling off period?,A cooling-off/look-up period is the time windo...
139,How do I withdraw my consent for sharing my cr...,You can withdraw your consent by contacting us...
140,How do I close my Flipkart EMI account?,In case you want to close your Flipkart EMI ac...
141,How do I contact your financial institution fo...,You can contact IDFC FIRST Bank at the followi...
142,What is Flipkart's credit card EMI payment opt...,"With Flipkart’s credit card EMI option, you ca..."
143,How does Flipkart prevent card fraud?,Online payments are monitored by our systems f...
144,Can I use any Debit Card to pay for my order?,You can choose to pay for your order on Flipka...
145,Can I use the Cash on Delivery payment option ...,The availability of Cash on Delivery option de...
146,How can I get the 3D Secure password for my Cr...,You can get a 3D Secure password by registerin...
147,How can I pay with a saved Credit/Debit Card?,Your saved cards can be seen when you choose t...
148,How does the 3D Secure password add security t...,The 3D Secure password is something that only ...
149,"If I have a saved card on Flipkart, will I be ...",Yes. Even if you've saved your card details on...
150,What is a 3D Secure password?,A 3D Secure password adds an extra layer of se...
151,What is the amount I can shop for with Cash on...,"You can shop up to Rs. 49,999 using Cash on De..."
152,Why is my card being saved on Flipkart?,It's quicker. You can save the hassle of typin...
153,What all card information does Flipkart store?,"We only store your card number, cardholder nam..."
154,Can I delete my saved cards?,"Yes, you can delete your saved cards at any gi..."
155,How many cards can I save on Flipkart?,"As of now, you can save upto 10 cards using th..."
156,What cards can I save on Flipkart?,"You can save any credit or debit VISA, MasterC..."
157,How do I save my card(s) on Flipkart?,Your card is saved automatically when you make...
158,How do I make a payment using a saved card?,You can view your saved cards by selecting the...
159,"If I have a saved card on Flipkart, will I be ...",Yes. Even if you have saved your card on Flipk...
160,How can I delete my saved card?,You can delete your saved card information on ...
161,What are the pre-requisites for using the save...,You should have a registered account with Flip...
162,Can I use a saved card to make an EMI payment?,"Yes, if your saved credit card is eligible for..."
163,I typed an incorrect card number by mistake wh...,"If you typed an incorrect card number, name or..."
164,Can I use my saved cards for making a payment ...,Absolutely! Any cards that you save on Flipkar...
165,What if I do not want my cards to be imported?,You can manage these cards from the 'Saved Car...
166,Can I use Credit/Debit Card to pay on Flipkart...,"Yes, you can use your Debit/Credit Card to sho..."
167,Can I combine the balance on my Gift Cards wit...,Cash on Delivery payments cannot be combined w...
168,I tried to make the payment for my Cash on Del...,Any amount debited will be credited back to th...
169,How can I convert my Cash on delivery order to...,"On your app, check if you are getting the 'Pay..."
170,I have updated my payment mode for my order bu...,"On your app, go to the 'Orders' page and you w..."
171,"My amount is debited twice for the order, what...",If the order value is debited twice from your ...
172,How can I pay for my order?,You can choose to conveniently pay for your or...
173,How do I pay using a credit or debit card?,You can choose the credit card or debit card p...
174,My amount has been debited but order has not b...,It may take up to 2 hours for your order confi...
175,Can I cancel my EMI after I've placed the orde...,Since payment modes cannot be changed after an...
176,Do I need to make a down payment to buy an ite...,"No, a down payment is not required for buying ..."
177,I chose the wrong EMI plan while making the pa...,EMI plan chosen while paying through the Bajaj...
178,Why can't I see Bajaj Finserv as a payment mod...,Bajaj Finserv No Cost EMI payment mode is avai...
179,Is Bajaj Finserv payment mode available on bot...,"Yes, the Bajaj Finserv payment mode is availab..."
180,I did not get the OTP while I was paying throu...,Please contact Bajaj Finserv at 08698010101 fo...
181,If I have paid for my order using the Bajaj Fi...,"Yes, you will get a complete refund to the ext..."
182,My payment from the 'Bajaj Finserv No Cost EMI...,Please contact Bajaj Finserv at 08698010101 fo...
183,How can I foreclose my EMI with Bajaj Finserv?,You can contact Bajaj Finserv at 08698010101 f...
184,How can I pay for my order using the Bajaj Fin...,"While paying for your order, choose 'Bajaj Fin..."
185,What are the EMI plans available if I pay usin...,Available EMI plans can be checked by clicking...
186,What is the credit limit on the Bajaj Finserv ...,The credit limit varies based on the type of B...
187,What is Bajaj Finserv payment mode?,Bajaj Finserv No Cost EMI' is a payment option...
188,How can I get a Bajaj Finserv EMI Network card?,You can check the eligibility and process of g...
189,What is the difference between Bajaj Finserv E...,If you make a payment using a Bajaj Finserv EM...
190,What are the benefits of the Bajaj Finserv pay...,"With Bajaj Finserv, you get a hassle-free paym..."
191,What is the pre-approved EMI limit for shoppin...,Please contact SBI’s Customer Care on 1800 425...
192,What are the EMI plans available if I choose t...,Different banks and card issuers offer varying...
193,What is pre-approved EMI?,This EMI option is available to select Flipkar...
194,What is EMI?,EMI is a payment option available on Flipkart ...
195,Can I buy any item using the 'Pre-approved EMI...,You can buy any item with a minimum value of ₹...
196,How is my EMI debited?,If you have paid for your order using the EMI ...
197,I have a query about the EMI charge. What shou...,You can get in touch with your card issuing ba...
198,What are the interest rates for the Credit car...,You will see the actual interest rates and the...

In [36]:
new_df.to_csv('faq_data.csv', index=False)